config/routes.rb
Rails.application.routes.draw do
  root "links#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete "logout", to: "sessions#delete"
  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :update, :edit, :destroy]

  namespace :api do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  include ActiveModel::Validations
  validate :check_valid_link
  belongs_to :user
  validates :title, presence: true
  validates :url, presence: true

  def check_valid_link
    uri = URI.parse(self.url)
    self.errors.add(:base, "Please submit a valid URL") unless uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :links
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def update
    link = Link.find_by(id: params[:id])
    respond_with link.update_attributes(link_params)
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :check_current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_current_user
    redirect_to login_path unless current_user
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :check_current_user

  def index
    @links = current_user.links
  end

  def create
    link = Link.new(link_params)
    if link.save
      current_user.links << link
      flash[:notice] = ["Link created!"]
      redirect_to links_path
    else
      flash[:errors] = link.errors.full_messages
      redirect_to links_path
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash[:notice] = "Successfully updated #{@link.title}"
      redirect_to links_path
    else
      flash[:error] = "Must submit a valid URL"
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id]).destroy
    redirect_to links_path
  end


  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if valid_user?
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:errors] = "Invalid login"
      render :new
    end
  end

  def delete
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def valid_user?
    @user = User.find_by(email: session_params[:email])
    @user && @user.authenticate(session_params[:password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    if params[:user][:confirmation] == params[:user][:password]
      @user = User.new(user_params)
      create_user
    else
      flash.now[:errors] = ["Confirmation does not match password"]
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def create_user
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<%= form_for @link do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/links/index.html.erb
<% if current_user %>
<%= link_to "Logout", logout_path, method: :delete %>
<% end %>
<%= form_for :link, url: links_path do |f| %>
  <h2>Add a New Link</h2>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.button 'Create New Link', class: 'btn-sm btn btn-default' %>
<% end %>
<br>


<h3>My Links</h3>
<input type='text' id='search' placeholder="Search">
<table class="table">
  <tr>
    <th>Title<small>(<a href="#" class='sortTitle'>sort alphabetically</a>)</small></th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th>Read?<a href="#" class='sortReadStatus'>sort</a></th>
  </tr>
  <% @links.each do |link| %>
    <tr data-id='<%= link.id %>' data-title='<%= link.title %>' class='<%= link.read %> link'>
      <td><%= link_to link.title %></td>
      <td><%= link_to link.url %></td>
      <td><%= link_to 'Edit', edit_link_path(link) %></td>
      <td><%= link_to 'Delete', link_path(link), method: 'delete' %></td>
      <% if link.read %>
        <td><%= link_to 'Yes', '#', id: 'read' %></td>
      <% else %>
        <td><%= link_to 'No', '#', id: 'read' %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<div class="well">
  <div class="btn btn-default btn-sm active" role="button">
    <%= link_to "Login", login_path, style: "color: blue;" %>
  </div>

  <h1>Create a new account</h1>

  <% if flash[:errors] %>
    <div class="errors">
    <% flash[:errors].each do |message| %>
      <%= message %>
    <% end %>
    </div>
  <% end %>

  <%= form_for(:user, url: users_path) do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email %> <br>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password %> <br>
      </div>

      <div class="form-group">
        <%= f.label :confirmation %>
        <%= f.password_field :confirmation %> <br>
      </div>

      <%= f.submit "Create Account", style: "color: black;", class: "btn btn-defatult" %>
    </div>
  <% end %>
</div>